"""
CrewAI Multi-Agent Template
Deployment: AWS ECS Fargate
Generated by: AWS Agentic AI Pattern Optimizer

Use Case: {{USE_CASE}}
Pattern: Task-based/Interaction-based, Multi-Agent
Framework: CrewAI
Deployment: AWS ECS Fargate with ALB

AWS Best Practices Implemented:
- Multi-tenant isolation via request context
- Role-based agent design
- Structured logging with tenant context
- Health checks and graceful shutdown
- Container-native monitoring
"""

import json
import os
import logging
import signal
import sys
from datetime import datetime
from typing import Optional, List
from functools import wraps

from crewai import Agent, Task, Crew, Process
from crewai.tools import tool
from langchain_aws import ChatBedrock
import boto3
from flask import Flask, request, jsonify
import structlog

# Configure structured logging
structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ]
)
logger = structlog.get_logger()

# Environment configuration
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
MODEL_ID = os.environ.get("MODEL_ID", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
PORT = int(os.environ.get("PORT", "8080"))

# Multi-tenant configuration
TENANT_ID_HEADER = "x-tenant-id"

# Flask application
app = Flask(__name__)


# =============================================================================
# Bedrock LLM Configuration
# =============================================================================

def create_bedrock_llm(tenant_id: str) -> ChatBedrock:
    """Create Bedrock LLM instance with tenant context.

    Args:
        tenant_id: Tenant identifier for request tagging

    Returns:
        Configured ChatBedrock instance
    """
    bedrock_client = boto3.client(
        "bedrock-runtime",
        region_name=AWS_REGION
    )

    return ChatBedrock(
        client=bedrock_client,
        model_id=MODEL_ID,
        model_kwargs={
            "max_tokens": 4096,
            "temperature": 0.7,
        }
    )


# =============================================================================
# Multi-Tenant Utilities
# =============================================================================

def extract_tenant_id() -> str:
    """Extract tenant ID from request headers.

    Returns:
        Tenant ID string

    Raises:
        ValueError: If tenant_id is not found
    """
    tenant_id = request.headers.get(TENANT_ID_HEADER)

    if not tenant_id:
        raise ValueError("Missing tenant_id in request headers")

    return tenant_id


def with_tenant_context(func):
    """Decorator to add tenant context to request handling."""
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            tenant_id = extract_tenant_id()
            request_id = request.headers.get("x-request-id", datetime.utcnow().isoformat())

            # Bind logging context
            log = logger.bind(
                tenant_id=tenant_id,
                request_id=request_id,
                endpoint=request.path
            )

            return func(tenant_id=tenant_id, request_id=request_id, log=log, *args, **kwargs)

        except ValueError as e:
            return jsonify({"error": str(e)}), 403

    return wrapper


# =============================================================================
# CrewAI Tools
# =============================================================================

@tool
def search_knowledge_base(query: str) -> str:
    """Search the knowledge base for relevant information.

    Args:
        query: Search query string

    Returns:
        Relevant information from knowledge base
    """
    # Implement knowledge base search (e.g., OpenSearch, Kendra)
    # This is a placeholder - replace with actual implementation
    return f"Knowledge base results for: {query}"


@tool
def analyze_data(data_description: str) -> str:
    """Analyze data based on description.

    Args:
        data_description: Description of data to analyze

    Returns:
        Analysis results
    """
    # Implement data analysis logic
    # This is a placeholder - replace with actual implementation
    return f"Analysis complete for: {data_description}"


@tool
def generate_report(content: str, format: str = "markdown") -> str:
    """Generate a formatted report.

    Args:
        content: Report content
        format: Output format (markdown, json, text)

    Returns:
        Formatted report
    """
    if format == "json":
        return json.dumps({"report": content})
    elif format == "markdown":
        return f"# Report\n\n{content}"
    else:
        return content


# =============================================================================
# Agent Definitions
# =============================================================================

def create_researcher_agent(llm: ChatBedrock) -> Agent:
    """Create the Researcher agent.

    The Researcher is responsible for gathering and analyzing information.

    Args:
        llm: Language model instance

    Returns:
        Configured Agent
    """
    return Agent(
        role="Senior Researcher",
        goal="Gather comprehensive, accurate information to support decision-making",
        backstory="""You are an expert researcher with years of experience in
        analyzing complex topics. You excel at finding relevant information,
        identifying patterns, and synthesizing insights from multiple sources.
        You always cite your sources and distinguish between facts and opinions.""",
        llm=llm,
        tools=[search_knowledge_base, analyze_data],
        verbose=True,
        allow_delegation=False
    )


def create_analyst_agent(llm: ChatBedrock) -> Agent:
    """Create the Analyst agent.

    The Analyst processes research findings and draws conclusions.

    Args:
        llm: Language model instance

    Returns:
        Configured Agent
    """
    return Agent(
        role="Senior Analyst",
        goal="Transform research into actionable insights and recommendations",
        backstory="""You are a seasoned analyst who excels at critical thinking
        and strategic analysis. You take complex information and distill it into
        clear, actionable recommendations. You consider multiple perspectives
        and potential outcomes in your analysis.""",
        llm=llm,
        tools=[analyze_data],
        verbose=True,
        allow_delegation=False
    )


def create_writer_agent(llm: ChatBedrock) -> Agent:
    """Create the Writer agent.

    The Writer produces the final deliverable.

    Args:
        llm: Language model instance

    Returns:
        Configured Agent
    """
    return Agent(
        role="Senior Writer",
        goal="Create clear, compelling, and well-structured content",
        backstory="""You are an accomplished writer who transforms complex
        analysis into engaging, easy-to-understand content. You have a talent
        for structuring information logically and writing in a way that
        resonates with your audience.""",
        llm=llm,
        tools=[generate_report],
        verbose=True,
        allow_delegation=False
    )


# =============================================================================
# Task Definitions
# =============================================================================

def create_research_task(topic: str, researcher: Agent) -> Task:
    """Create the research task.

    Args:
        topic: Topic to research
        researcher: Researcher agent

    Returns:
        Configured Task
    """
    return Task(
        description=f"""Research the following topic thoroughly:

Topic: {topic}

Your research should:
1. Identify key facts and data points
2. Find relevant examples and case studies
3. Note any conflicting information or debates
4. Highlight important trends or patterns

Provide a comprehensive research summary.""",
        expected_output="A detailed research summary with key findings, data points, and sources",
        agent=researcher
    )


def create_analysis_task(analyst: Agent, context_tasks: List[Task]) -> Task:
    """Create the analysis task.

    Args:
        analyst: Analyst agent
        context_tasks: Tasks providing context (research task)

    Returns:
        Configured Task
    """
    return Task(
        description="""Analyze the research findings and develop insights:

Based on the research provided:
1. Identify the most important findings
2. Draw conclusions from the data
3. Identify potential risks and opportunities
4. Develop actionable recommendations

Provide a thorough analysis with clear recommendations.""",
        expected_output="A strategic analysis with key insights, conclusions, and actionable recommendations",
        agent=analyst,
        context=context_tasks
    )


def create_writing_task(writer: Agent, context_tasks: List[Task]) -> Task:
    """Create the writing task.

    Args:
        writer: Writer agent
        context_tasks: Tasks providing context (research and analysis tasks)

    Returns:
        Configured Task
    """
    return Task(
        description="""Create a comprehensive final report:

Using the research and analysis provided:
1. Structure the content logically
2. Write clear, engaging prose
3. Include an executive summary
4. Add conclusions and next steps

The report should be professional and actionable.""",
        expected_output="A well-structured, professional report with executive summary, findings, analysis, and recommendations",
        agent=writer,
        context=context_tasks
    )


# =============================================================================
# Crew Assembly
# =============================================================================

def create_crew(topic: str, tenant_id: str) -> Crew:
    """Assemble the multi-agent crew for the task.

    Args:
        topic: The topic/task to work on
        tenant_id: Tenant identifier

    Returns:
        Configured Crew
    """
    # Create LLM with tenant context
    llm = create_bedrock_llm(tenant_id)

    # Create agents
    researcher = create_researcher_agent(llm)
    analyst = create_analyst_agent(llm)
    writer = create_writer_agent(llm)

    # Create tasks
    research_task = create_research_task(topic, researcher)
    analysis_task = create_analysis_task(analyst, [research_task])
    writing_task = create_writing_task(writer, [research_task, analysis_task])

    # Assemble crew
    crew = Crew(
        agents=[researcher, analyst, writer],
        tasks=[research_task, analysis_task, writing_task],
        process=Process.sequential,  # Tasks execute in order
        verbose=True
    )

    return crew


# =============================================================================
# API Endpoints
# =============================================================================

@app.route("/health", methods=["GET"])
def health_check():
    """Health check endpoint for ALB."""
    return jsonify({"status": "healthy", "timestamp": datetime.utcnow().isoformat()})


@app.route("/ready", methods=["GET"])
def readiness_check():
    """Readiness check endpoint."""
    # Add any dependency checks here (DB, cache, etc.)
    return jsonify({"status": "ready", "timestamp": datetime.utcnow().isoformat()})


@app.route("/execute", methods=["POST"])
@with_tenant_context
def execute_crew(tenant_id: str, request_id: str, log):
    """Execute the multi-agent crew on a task.

    Expected request body:
    {
        "task": "The task/topic for the crew to work on"
    }
    """
    log.info("crew_execution_started")

    try:
        # Parse request
        body = request.get_json()
        task_input = body.get("task")

        if not task_input:
            return jsonify({"error": "Missing 'task' in request body"}), 400

        # Create and execute crew
        crew = create_crew(task_input, tenant_id)

        log.info("crew_kickoff", task=task_input[:100])
        result = crew.kickoff()

        log.info("crew_execution_completed", result_length=len(str(result)))

        return jsonify({
            "result": str(result),
            "request_id": request_id,
            "agents_used": ["researcher", "analyst", "writer"],
            "process": "sequential"
        })

    except Exception as e:
        log.error("crew_execution_failed", error=str(e))
        return jsonify({
            "error": str(e),
            "request_id": request_id
        }), 500


@app.route("/agents", methods=["GET"])
@with_tenant_context
def list_agents(tenant_id: str, request_id: str, log):
    """List available agents and their roles."""
    agents = [
        {
            "name": "researcher",
            "role": "Senior Researcher",
            "goal": "Gather comprehensive, accurate information"
        },
        {
            "name": "analyst",
            "role": "Senior Analyst",
            "goal": "Transform research into actionable insights"
        },
        {
            "name": "writer",
            "role": "Senior Writer",
            "goal": "Create clear, compelling content"
        }
    ]

    return jsonify({
        "agents": agents,
        "process": "sequential",
        "request_id": request_id
    })


# =============================================================================
# Graceful Shutdown
# =============================================================================

def graceful_shutdown(signum, frame):
    """Handle graceful shutdown on SIGTERM."""
    logger.info("shutdown_initiated", signal=signum)
    # Add cleanup logic here (close connections, etc.)
    sys.exit(0)


signal.signal(signal.SIGTERM, graceful_shutdown)
signal.signal(signal.SIGINT, graceful_shutdown)


# =============================================================================
# Main Entry Point
# =============================================================================

if __name__ == "__main__":
    logger.info("application_starting", port=PORT)

    # Run Flask app
    app.run(
        host="0.0.0.0",
        port=PORT,
        debug=os.environ.get("DEBUG", "false").lower() == "true"
    )
