"""
Strands Agents SDK Task-Based Single-Agent Template
Deployment: AWS Lambda
Generated by: AWS Agentic AI Pattern Optimizer

Use Case: {{USE_CASE}}
Pattern: Task-based, Single Agent
Framework: Strands Agents SDK
Deployment: AWS Lambda with API Gateway

AWS Best Practices Implemented:
- Native AWS integration
- Multi-tenant isolation via request tagging
- Least privilege IAM
- Structured logging with tenant context
- X-Ray tracing
"""

import json
import os
import logging
from datetime import datetime
from typing import Optional, Any

from strands import Agent
from strands.models import BedrockModel
from strands.tools import tool
import boto3
from aws_xray_sdk.core import xray_recorder
from aws_xray_sdk.core import patch_all

# Enable X-Ray tracing
patch_all()

# Configure logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Environment configuration
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
MODEL_ID = os.environ.get("MODEL_ID", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
MAX_TOKENS = int(os.environ.get("MAX_TOKENS", "4096"))

# Multi-tenant configuration
TENANT_ID_HEADER = "x-tenant-id"


# =============================================================================
# Utility Functions
# =============================================================================

def extract_tenant_id(event: dict) -> str:
    """Extract tenant ID from API Gateway event.

    Args:
        event: API Gateway event

    Returns:
        Tenant ID string

    Raises:
        ValueError: If tenant_id is not found
    """
    # Try authorizer context first
    tenant_id = (
        event.get("requestContext", {})
        .get("authorizer", {})
        .get("tenant_id")
    )

    # Fallback to header
    if not tenant_id:
        headers = event.get("headers", {})
        tenant_id = headers.get(TENANT_ID_HEADER) or headers.get(TENANT_ID_HEADER.lower())

    if not tenant_id:
        raise ValueError("Missing tenant_id in request")

    return tenant_id


def log_with_context(level: str, message: str, tenant_id: str, request_id: str, **kwargs):
    """Log with tenant and request context."""
    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "level": level,
        "message": message,
        "tenant_id": tenant_id,
        "request_id": request_id,
        **kwargs
    }
    if level == "ERROR":
        logger.error(json.dumps(log_entry))
    elif level == "WARNING":
        logger.warning(json.dumps(log_entry))
    else:
        logger.info(json.dumps(log_entry))


# =============================================================================
# Tool Definitions
# =============================================================================

@tool
def search_database(query: str, tenant_id: str) -> str:
    """Search the tenant's database for relevant information.

    Args:
        query: Search query
        tenant_id: Tenant identifier for data isolation

    Returns:
        Search results as string
    """
    # Implement tenant-isolated database search
    # Example: Query DynamoDB with tenant partition key
    dynamodb = boto3.resource("dynamodb", region_name=AWS_REGION)
    # table = dynamodb.Table("your-table")
    # response = table.query(
    #     KeyConditionExpression=Key("pk").eq(f"TENANT#{tenant_id}")
    # )

    # Placeholder implementation
    return f"Database search results for tenant {tenant_id}: {query}"


@tool
def call_external_api(endpoint: str, method: str = "GET", body: Optional[dict] = None) -> str:
    """Call an external API endpoint.

    Args:
        endpoint: API endpoint URL (must be HTTPS and resolve to a public IP)
        method: HTTP method (GET, POST, etc.)
        body: Request body for POST/PUT requests

    Returns:
        API response as string
    """
    import urllib.request
    import urllib.error
    import socket
    import ipaddress
    from urllib.parse import urlparse

    # SSRF protection: enforce HTTPS and block requests to private, loopback,
    # link-local (incl. the 169.254.169.254 instance metadata endpoint),
    # and other non-public address ranges.
    parsed = urlparse(endpoint)
    if parsed.scheme != "https":
        return "API call rejected: only HTTPS endpoints are allowed"
    if not parsed.hostname:
        return "API call rejected: invalid endpoint URL"

    try:
        resolved = socket.getaddrinfo(parsed.hostname, parsed.port or 443, proto=socket.IPPROTO_TCP)
    except socket.gaierror as e:
        return f"API call rejected: DNS resolution failed ({e})"

    for family, _, _, _, sockaddr in resolved:
        ip = ipaddress.ip_address(sockaddr[0])
        if (
            ip.is_private
            or ip.is_loopback
            or ip.is_link_local
            or ip.is_reserved
            or ip.is_multicast
            or ip.is_unspecified
        ):
            return "API call rejected: endpoint resolves to a non-public address"

    try:
        req = urllib.request.Request(endpoint, method=method)
        if body:
            req.data = json.dumps(body).encode()
            req.add_header("Content-Type", "application/json")

        with urllib.request.urlopen(req, timeout=30) as response:  # nosec B310 - scheme validated above
            return response.read().decode()

    except urllib.error.URLError as e:
        return f"API call failed: {str(e)}"


@tool
def store_result(key: str, value: str, tenant_id: str) -> str:
    """Store a result in tenant-isolated storage.

    Args:
        key: Storage key
        value: Value to store
        tenant_id: Tenant identifier

    Returns:
        Confirmation message
    """
    # Implement tenant-isolated storage
    # Example: Store in DynamoDB or S3 with tenant prefix

    # Placeholder implementation
    return f"Stored {key} for tenant {tenant_id}"


@tool
def calculate(expression: str) -> str:
    """Safely evaluate a mathematical expression.

    Args:
        expression: Mathematical expression to evaluate

    Returns:
        Calculation result
    """
    # Safe eval for math expressions
    import ast
    import operator

    allowed_operators = {
        ast.Add: operator.add,
        ast.Sub: operator.sub,
        ast.Mult: operator.mul,
        ast.Div: operator.truediv,
        ast.Pow: operator.pow,
        ast.USub: operator.neg,
    }

    def safe_eval(node):
        if isinstance(node, ast.Num):
            return node.n
        elif isinstance(node, ast.BinOp):
            left = safe_eval(node.left)
            right = safe_eval(node.right)
            return allowed_operators[type(node.op)](left, right)
        elif isinstance(node, ast.UnaryOp):
            operand = safe_eval(node.operand)
            return allowed_operators[type(node.op)](operand)
        else:
            raise ValueError(f"Unsupported operation: {type(node)}")

    try:
        tree = ast.parse(expression, mode="eval")
        result = safe_eval(tree.body)
        return str(result)
    except Exception as e:
        return f"Calculation error: {str(e)}"


# =============================================================================
# Agent Factory
# =============================================================================

class TenantAwareAgent:
    """Wrapper for Strands Agent with tenant context."""

    def __init__(self, tenant_id: str, request_id: str):
        """Initialize agent with tenant context.

        Args:
            tenant_id: Tenant identifier
            request_id: Request identifier for tracing
        """
        self.tenant_id = tenant_id
        self.request_id = request_id

        # Create Bedrock model
        self.model = BedrockModel(
            model_id=MODEL_ID,
            region_name=AWS_REGION
        )

        # Create agent with tools
        self.agent = Agent(
            model=self.model,
            system_prompt=self._build_system_prompt(),
            tools=[
                search_database,
                call_external_api,
                store_result,
                calculate
            ]
        )

    def _build_system_prompt(self) -> str:
        """Build system prompt with tenant context."""
        return f"""You are a helpful AI assistant operating in a multi-tenant environment.

Current Context:
- Tenant ID: {self.tenant_id}
- Request ID: {self.request_id}

Guidelines:
1. Always consider the tenant context when accessing data
2. Use tools appropriately to complete tasks
3. Be concise but thorough in your responses
4. If you're unsure about something, ask for clarification
5. Prioritize security and data isolation

Your capabilities:
- Search the tenant's database for information
- Call external APIs when needed
- Store results for future reference
- Perform calculations

Complete tasks efficiently while maintaining data isolation between tenants."""

    @xray_recorder.capture("agent_run")
    def run(self, task: str) -> dict:
        """Execute a task with the agent.

        Args:
            task: Task description

        Returns:
            Dictionary with result and metadata
        """
        log_with_context(
            "INFO",
            "Agent execution started",
            self.tenant_id,
            self.request_id,
            task_length=len(task)
        )

        try:
            # Execute agent
            result = self.agent(task)

            log_with_context(
                "INFO",
                "Agent execution completed",
                self.tenant_id,
                self.request_id,
                result_length=len(str(result))
            )

            return {
                "success": True,
                "result": str(result),
                "tenant_id": self.tenant_id,
                "request_id": self.request_id
            }

        except Exception as e:
            log_with_context(
                "ERROR",
                "Agent execution failed",
                self.tenant_id,
                self.request_id,
                error=str(e)
            )

            return {
                "success": False,
                "error": str(e),
                "tenant_id": self.tenant_id,
                "request_id": self.request_id
            }


# =============================================================================
# Lambda Handler
# =============================================================================

def lambda_handler(event: dict, context: Any) -> dict:
    """AWS Lambda handler for the Strands agent.

    Expected request body:
    {
        "task": "The task to complete"
    }

    Args:
        event: API Gateway event
        context: Lambda context

    Returns:
        API Gateway response
    """
    request_id = context.aws_request_id if context else f"local-{datetime.utcnow().isoformat()}"

    try:
        # Extract tenant ID
        tenant_id = extract_tenant_id(event)

        log_with_context(
            "INFO",
            "Request received",
            tenant_id,
            request_id
        )

        # Parse request body
        body = json.loads(event.get("body", "{}"))
        task = body.get("task")

        if not task:
            return {
                "statusCode": 400,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({
                    "error": "Missing 'task' in request body",
                    "request_id": request_id
                })
            }

        # Create and run agent
        agent = TenantAwareAgent(tenant_id, request_id)
        result = agent.run(task)

        if result["success"]:
            return {
                "statusCode": 200,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({
                    "result": result["result"],
                    "request_id": request_id
                })
            }
        else:
            return {
                "statusCode": 500,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({
                    "error": result["error"],
                    "request_id": request_id
                })
            }

    except ValueError as e:
        return {
            "statusCode": 403,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": str(e),
                "request_id": request_id
            })
        }

    except json.JSONDecodeError:
        return {
            "statusCode": 400,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": "Invalid JSON in request body",
                "request_id": request_id
            })
        }

    except Exception as e:
        logger.exception("Unexpected error")
        return {
            "statusCode": 500,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": "Internal server error",
                "request_id": request_id
            })
        }


# =============================================================================
# Streaming Handler (for longer tasks)
# =============================================================================

def lambda_handler_streaming(event: dict, context: Any):
    """Streaming handler for longer-running tasks.

    Uses Lambda response streaming for real-time output.
    """
    # Note: Requires Lambda function URL with response streaming enabled
    # Implementation similar to above but yields chunks
    pass


# =============================================================================
# Local Testing
# =============================================================================

if __name__ == "__main__":
    test_event = {
        "requestContext": {
            "authorizer": {
                "tenant_id": "test-tenant-123"
            }
        },
        "body": json.dumps({
            "task": "{{USE_CASE}}"
        })
    }

    class MockContext:
        aws_request_id = "local-test-123"

    result = lambda_handler(test_event, MockContext())
    print(json.dumps(json.loads(result["body"]), indent=2))
