"""
LangGraph Interaction-Based Multi-Agent Template
Deployment: AWS ECS Fargate
Generated by: AWS Agentic AI Pattern Optimizer

Use Case: {{USE_CASE}}
Pattern: Interaction-based, Multi-Agent
Framework: LangGraph
Deployment: AWS ECS Fargate with ALB

AWS Best Practices Implemented:
- Multi-tenant isolation via request context
- Conversational state management
- Multi-agent graph with supervisor pattern
- Structured logging with tenant context
- Health checks and graceful shutdown
"""

import json
import os
import logging
import signal
import sys
from datetime import datetime
from typing import TypedDict, List, Annotated, Literal, Optional
from functools import reduce
import operator

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langchain_aws import ChatBedrock
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage, BaseMessage
import boto3
from flask import Flask, request, jsonify, Response
import structlog

# Configure structured logging
structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ]
)
logger = structlog.get_logger()

# Environment configuration
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
MODEL_ID = os.environ.get("MODEL_ID", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
PORT = int(os.environ.get("PORT", "8080"))

# Multi-tenant configuration
TENANT_ID_HEADER = "x-tenant-id"

# Flask application
app = Flask(__name__)

# In-memory conversation store (use Redis/DynamoDB in production)
conversation_store = {}


# =============================================================================
# State Definition
# =============================================================================

def add_messages(left: List[BaseMessage], right: List[BaseMessage]) -> List[BaseMessage]:
    """Reducer for combining message lists."""
    return left + right


class ConversationState(TypedDict):
    """State for multi-agent conversation.

    Attributes:
        messages: Conversation history
        tenant_id: Tenant identifier
        session_id: Conversation session ID
        current_agent: Which agent is currently active
        agent_outputs: Outputs from each agent
        metadata: Additional metadata
    """
    messages: Annotated[List[BaseMessage], add_messages]
    tenant_id: str
    session_id: str
    current_agent: str
    agent_outputs: dict
    metadata: dict


# =============================================================================
# Utility Functions
# =============================================================================

def extract_tenant_id() -> str:
    """Extract tenant ID from request headers."""
    tenant_id = request.headers.get(TENANT_ID_HEADER)
    if not tenant_id:
        raise ValueError("Missing tenant_id in request headers")
    return tenant_id


def create_bedrock_llm(tenant_id: str) -> ChatBedrock:
    """Create Bedrock LLM instance with tenant context."""
    bedrock_client = boto3.client(
        "bedrock-runtime",
        region_name=AWS_REGION
    )

    return ChatBedrock(
        client=bedrock_client,
        model_id=MODEL_ID,
        model_kwargs={
            "max_tokens": 4096,
            "temperature": 0.7,
        }
    )


# =============================================================================
# Agent Definitions
# =============================================================================

def supervisor_agent(state: ConversationState) -> ConversationState:
    """Supervisor agent that routes conversations to appropriate specialists.

    Analyzes the user's message and determines which specialist agent
    should handle the request.
    """
    llm = create_bedrock_llm(state["tenant_id"])

    system_prompt = """You are a supervisor agent that routes user requests to specialists.

Available specialists:
- RESEARCHER: For questions requiring information lookup or analysis
- ASSISTANT: For general questions and task completion
- SPECIALIST: For domain-specific technical questions

Analyze the user's message and respond with ONLY the agent name to route to.
If the conversation seems complete, respond with FINISH."""

    last_message = state["messages"][-1] if state["messages"] else None
    if not last_message:
        state["current_agent"] = "assistant"
        return state

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Route this message: {last_message.content}")
    ])

    routing = response.content.strip().upper()

    if "RESEARCHER" in routing:
        state["current_agent"] = "researcher"
    elif "SPECIALIST" in routing:
        state["current_agent"] = "specialist"
    elif "FINISH" in routing:
        state["current_agent"] = "finish"
    else:
        state["current_agent"] = "assistant"

    return state


def researcher_agent(state: ConversationState) -> ConversationState:
    """Researcher agent for information gathering and analysis."""
    llm = create_bedrock_llm(state["tenant_id"])

    system_prompt = """You are a research specialist. Your role is to:
1. Analyze questions thoroughly
2. Provide well-researched, accurate information
3. Cite sources when possible
4. Ask clarifying questions if needed

Be thorough but concise in your responses."""

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        *state["messages"]
    ])

    state["messages"] = [response]
    state["agent_outputs"]["researcher"] = response.content
    return state


def assistant_agent(state: ConversationState) -> ConversationState:
    """General assistant agent for conversation and task completion."""
    llm = create_bedrock_llm(state["tenant_id"])

    system_prompt = """You are a helpful assistant. Your role is to:
1. Provide clear, helpful responses
2. Complete tasks as requested
3. Maintain a friendly, professional tone
4. Ask for clarification when needed

Be concise but thorough."""

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        *state["messages"]
    ])

    state["messages"] = [response]
    state["agent_outputs"]["assistant"] = response.content
    return state


def specialist_agent(state: ConversationState) -> ConversationState:
    """Specialist agent for domain-specific technical questions."""
    llm = create_bedrock_llm(state["tenant_id"])

    system_prompt = """You are a technical specialist. Your role is to:
1. Provide expert-level technical guidance
2. Explain complex concepts clearly
3. Offer best practices and recommendations
4. Be precise and accurate

Focus on technical accuracy while remaining accessible."""

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        *state["messages"]
    ])

    state["messages"] = [response]
    state["agent_outputs"]["specialist"] = response.content
    return state


# =============================================================================
# Graph Construction
# =============================================================================

def route_to_agent(state: ConversationState) -> str:
    """Route to the appropriate agent based on supervisor decision."""
    return state["current_agent"]


def create_conversation_graph() -> StateGraph:
    """Create the multi-agent conversation graph."""
    workflow = StateGraph(ConversationState)

    # Add nodes
    workflow.add_node("supervisor", supervisor_agent)
    workflow.add_node("researcher", researcher_agent)
    workflow.add_node("assistant", assistant_agent)
    workflow.add_node("specialist", specialist_agent)

    # Define edges
    workflow.set_entry_point("supervisor")

    workflow.add_conditional_edges(
        "supervisor",
        route_to_agent,
        {
            "researcher": "researcher",
            "assistant": "assistant",
            "specialist": "specialist",
            "finish": END
        }
    )

    # All agents return to supervisor for potential follow-up
    workflow.add_edge("researcher", END)
    workflow.add_edge("assistant", END)
    workflow.add_edge("specialist", END)

    # Use memory saver for conversation persistence
    memory = MemorySaver()
    return workflow.compile(checkpointer=memory)


# Initialize graph at module load
conversation_graph = create_conversation_graph()


# =============================================================================
# API Endpoints
# =============================================================================

@app.route("/health", methods=["GET"])
def health_check():
    """Health check endpoint for ALB."""
    return jsonify({"status": "healthy", "timestamp": datetime.utcnow().isoformat()})


@app.route("/ready", methods=["GET"])
def readiness_check():
    """Readiness check endpoint."""
    return jsonify({"status": "ready", "timestamp": datetime.utcnow().isoformat()})


@app.route("/chat", methods=["POST"])
def chat():
    """Handle chat messages in a conversation.

    Expected request body:
    {
        "message": "User's message",
        "session_id": "optional-session-id"
    }
    """
    try:
        tenant_id = extract_tenant_id()
        request_id = request.headers.get("x-request-id", datetime.utcnow().isoformat())

        log = logger.bind(
            tenant_id=tenant_id,
            request_id=request_id
        )

        body = request.get_json()
        message = body.get("message")
        session_id = body.get("session_id", f"{tenant_id}-{datetime.utcnow().timestamp()}")

        if not message:
            return jsonify({"error": "Missing 'message' in request body"}), 400

        log.info("chat_request", session_id=session_id, message_length=len(message))

        # Get or create conversation state
        conversation_key = f"{tenant_id}:{session_id}"
        existing_messages = conversation_store.get(conversation_key, [])

        # Create initial state
        initial_state: ConversationState = {
            "messages": existing_messages + [HumanMessage(content=message)],
            "tenant_id": tenant_id,
            "session_id": session_id,
            "current_agent": "",
            "agent_outputs": {},
            "metadata": {
                "request_id": request_id,
                "timestamp": datetime.utcnow().isoformat()
            }
        }

        # Run the conversation graph
        config = {"configurable": {"thread_id": conversation_key}}
        final_state = conversation_graph.invoke(initial_state, config)

        # Store updated conversation
        conversation_store[conversation_key] = final_state["messages"]

        # Get the last AI response
        ai_messages = [m for m in final_state["messages"] if isinstance(m, AIMessage)]
        response_content = ai_messages[-1].content if ai_messages else "I couldn't process that request."

        log.info("chat_response", session_id=session_id, agent=final_state.get("current_agent"))

        return jsonify({
            "response": response_content,
            "session_id": session_id,
            "agent_used": final_state.get("current_agent"),
            "request_id": request_id
        })

    except ValueError as e:
        return jsonify({"error": str(e)}), 403
    except Exception as e:
        logger.error("chat_error", error=str(e))
        return jsonify({"error": "Internal server error"}), 500


@app.route("/sessions/<session_id>", methods=["GET"])
def get_session():
    """Get conversation history for a session."""
    try:
        tenant_id = extract_tenant_id()
        session_id = request.view_args.get("session_id")

        conversation_key = f"{tenant_id}:{session_id}"
        messages = conversation_store.get(conversation_key, [])

        history = [
            {
                "role": "user" if isinstance(m, HumanMessage) else "assistant",
                "content": m.content
            }
            for m in messages
        ]

        return jsonify({
            "session_id": session_id,
            "message_count": len(messages),
            "history": history
        })

    except ValueError as e:
        return jsonify({"error": str(e)}), 403


@app.route("/sessions/<session_id>", methods=["DELETE"])
def delete_session():
    """Clear a conversation session."""
    try:
        tenant_id = extract_tenant_id()
        session_id = request.view_args.get("session_id")

        conversation_key = f"{tenant_id}:{session_id}"
        if conversation_key in conversation_store:
            del conversation_store[conversation_key]

        return jsonify({"status": "deleted", "session_id": session_id})

    except ValueError as e:
        return jsonify({"error": str(e)}), 403


# =============================================================================
# Graceful Shutdown
# =============================================================================

def graceful_shutdown(signum, frame):
    """Handle graceful shutdown on SIGTERM."""
    logger.info("shutdown_initiated", signal=signum)
    # Save any pending state to persistent store
    sys.exit(0)


signal.signal(signal.SIGTERM, graceful_shutdown)
signal.signal(signal.SIGINT, graceful_shutdown)


# =============================================================================
# Main Entry Point
# =============================================================================

if __name__ == "__main__":
    logger.info("application_starting", port=PORT)
    app.run(host="0.0.0.0", port=PORT, debug=os.environ.get("DEBUG", "false").lower() == "true")
