# =============================================================================
# Terraform Configuration for Lambda Deployment
# Generated by: AWS Agentic AI Pattern Optimizer
#
# Use Case: {{USE_CASE}}
# Deployment: AWS Lambda with API Gateway
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0"
    }
  }
}

# =============================================================================
# Variables
# =============================================================================

variable "tenant_id" {
  description = "Tenant identifier for resource tagging and isolation"
  type        = string
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region for deployment"
  type        = string
  default     = "us-east-1"
}

variable "model_id" {
  description = "Bedrock model ID"
  type        = string
  default     = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
}

variable "lambda_memory" {
  description = "Lambda function memory in MB"
  type        = number
  default     = 1024
}

variable "lambda_timeout" {
  description = "Lambda function timeout in seconds"
  type        = number
  default     = 900
}

variable "allowed_origins" {
  description = "Allowed CORS origins. Set to your known front-end domain(s); do NOT use [\"*\"] for an authenticated endpoint."
  type        = list(string)
  default     = []
}

variable "jwt_issuer" {
  description = "JWT issuer URL for the API Gateway authorizer (e.g. a Cognito user pool: https://cognito-idp.<region>.amazonaws.com/<user-pool-id>)."
  type        = string
}

variable "jwt_audience" {
  description = "Accepted JWT audiences (e.g. the Cognito app client IDs)."
  type        = list(string)
}

# =============================================================================
# Provider Configuration
# =============================================================================

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      TenantId    = var.tenant_id
      Environment = var.environment
      Application = "agentic-ai"
      ManagedBy   = "terraform"
    }
  }
}

# =============================================================================
# Data Sources
# =============================================================================

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# =============================================================================
# IAM Role for Lambda
# =============================================================================

resource "aws_iam_role" "lambda_execution" {
  name = "agentic-ai-lambda-${var.tenant_id}-${var.environment}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# Bedrock access policy
resource "aws_iam_role_policy" "bedrock_access" {
  name = "bedrock-access"
  role = aws_iam_role.lambda_execution.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "BedrockInvoke"
        Effect = "Allow"
        Action = [
          "bedrock:InvokeModel",
          "bedrock:InvokeModelWithResponseStream"
        ]
        Resource = [
          "arn:aws:bedrock:${var.aws_region}::foundation-model/anthropic.*",
          "arn:aws:bedrock:${var.aws_region}::foundation-model/us.anthropic.*"
        ]
      }
    ]
  })
}

# CloudWatch Logs policy
resource "aws_iam_role_policy_attachment" "lambda_logs" {
  role       = aws_iam_role.lambda_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# X-Ray tracing policy
resource "aws_iam_role_policy_attachment" "xray_access" {
  role       = aws_iam_role.lambda_execution.name
  policy_arn = "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
}

# =============================================================================
# Lambda Function
# =============================================================================

# Package the Lambda code
data "archive_file" "lambda_package" {
  type        = "zip"
  source_dir  = "${path.module}/../src"
  output_path = "${path.module}/lambda_package.zip"
}

resource "aws_lambda_function" "agent" {
  filename         = data.archive_file.lambda_package.output_path
  function_name    = "agentic-ai-${var.tenant_id}-${var.environment}"
  role             = aws_iam_role.lambda_execution.arn
  handler          = "agent.lambda_handler"
  source_code_hash = data.archive_file.lambda_package.output_base64sha256
  runtime          = "python3.11"
  architectures    = ["arm64"] # Cost optimization with Graviton

  timeout     = var.lambda_timeout
  memory_size = var.lambda_memory

  environment {
    variables = {
      TENANT_ID   = var.tenant_id
      ENVIRONMENT = var.environment
      AWS_REGION  = var.aws_region
      MODEL_ID    = var.model_id
    }
  }

  tracing_config {
    mode = "Active"
  }

  # Reserved concurrency for tenant isolation
  reserved_concurrent_executions = 50
}

# CloudWatch Log Group with retention
resource "aws_cloudwatch_log_group" "lambda_logs" {
  name              = "/aws/lambda/${aws_lambda_function.agent.function_name}"
  retention_in_days = 30
}

# =============================================================================
# API Gateway
# =============================================================================

resource "aws_apigatewayv2_api" "agent_api" {
  name          = "agentic-ai-api-${var.tenant_id}-${var.environment}"
  protocol_type = "HTTP"

  cors_configuration {
    allow_origins = var.allowed_origins
    allow_methods = ["POST", "OPTIONS"]
    allow_headers = ["Content-Type", "Authorization", "x-tenant-id"]
    max_age       = 300
  }
}

resource "aws_apigatewayv2_integration" "lambda" {
  api_id             = aws_apigatewayv2_api.agent_api.id
  integration_type   = "AWS_PROXY"
  integration_uri    = aws_lambda_function.agent.invoke_arn
  integration_method = "POST"
}

# JWT authorizer (e.g. Amazon Cognito). Requires a valid bearer token on every
# request; the route below is protected by it so the endpoint is not public.
resource "aws_apigatewayv2_authorizer" "jwt" {
  api_id           = aws_apigatewayv2_api.agent_api.id
  authorizer_type  = "JWT"
  identity_sources = ["$request.header.Authorization"]
  name             = "agentic-ai-jwt-${var.tenant_id}-${var.environment}"

  jwt_configuration {
    audience = var.jwt_audience
    issuer   = var.jwt_issuer
  }
}

resource "aws_apigatewayv2_route" "execute" {
  api_id             = aws_apigatewayv2_api.agent_api.id
  route_key          = "POST /execute"
  target             = "integrations/${aws_apigatewayv2_integration.lambda.id}"
  authorization_type = "JWT"
  authorizer_id      = aws_apigatewayv2_authorizer.jwt.id
}

resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.agent_api.id
  name        = var.environment
  auto_deploy = true

  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.api_logs.arn
    format = jsonencode({
      requestId      = "$context.requestId"
      ip             = "$context.identity.sourceIp"
      requestTime    = "$context.requestTime"
      httpMethod     = "$context.httpMethod"
      routeKey       = "$context.routeKey"
      status         = "$context.status"
      protocol       = "$context.protocol"
      responseLength = "$context.responseLength"
      errorMessage   = "$context.error.message"
    })
  }

  default_route_settings {
    throttling_rate_limit  = 100
    throttling_burst_limit = 50
  }
}

resource "aws_cloudwatch_log_group" "api_logs" {
  name              = "/aws/apigateway/agentic-ai-${var.tenant_id}-${var.environment}"
  retention_in_days = 30
}

# Lambda permission for API Gateway
resource "aws_lambda_permission" "api_gateway" {
  statement_id  = "AllowAPIGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.agent.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.agent_api.execution_arn}/*/*"
}

# =============================================================================
# CloudWatch Alarms
# =============================================================================

resource "aws_cloudwatch_metric_alarm" "lambda_errors" {
  alarm_name          = "agentic-ai-errors-${var.tenant_id}-${var.environment}"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "Errors"
  namespace           = "AWS/Lambda"
  period              = 300
  statistic           = "Sum"
  threshold           = 5
  alarm_description   = "Lambda function error rate alarm"

  dimensions = {
    FunctionName = aws_lambda_function.agent.function_name
  }

  alarm_actions = [] # Add SNS topic ARN for notifications
}

resource "aws_cloudwatch_metric_alarm" "lambda_duration" {
  alarm_name          = "agentic-ai-duration-${var.tenant_id}-${var.environment}"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "Duration"
  namespace           = "AWS/Lambda"
  period              = 300
  statistic           = "Average"
  threshold           = var.lambda_timeout * 1000 * 0.8 # 80% of timeout
  alarm_description   = "Lambda function duration approaching timeout"

  dimensions = {
    FunctionName = aws_lambda_function.agent.function_name
  }

  alarm_actions = [] # Add SNS topic ARN for notifications
}

# =============================================================================
# Outputs
# =============================================================================

output "api_endpoint" {
  description = "API Gateway endpoint URL"
  value       = "${aws_apigatewayv2_stage.default.invoke_url}/execute"
}

output "lambda_function_name" {
  description = "Lambda function name"
  value       = aws_lambda_function.agent.function_name
}

output "lambda_function_arn" {
  description = "Lambda function ARN"
  value       = aws_lambda_function.agent.arn
}

output "cloudwatch_log_group" {
  description = "CloudWatch log group name"
  value       = aws_cloudwatch_log_group.lambda_logs.name
}
