"""
LangGraph Task-Based Single-Agent Template
Deployment: AWS Lambda
Generated by: AWS Agentic AI Pattern Optimizer

Use Case: {{USE_CASE}}
Pattern: Task-based, Single Agent
Framework: LangGraph
Deployment: AWS Lambda with API Gateway

AWS Best Practices Implemented:
- Multi-tenant isolation via request tagging
- Least privilege IAM
- Structured logging with tenant context
- X-Ray tracing
- Error handling with graceful degradation
"""

import json
import os
import logging
from datetime import datetime
from typing import TypedDict, List, Annotated, Optional
from functools import reduce

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langchain_aws import ChatBedrock
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
import boto3
from aws_xray_sdk.core import xray_recorder
from aws_xray_sdk.core import patch_all

# Enable X-Ray tracing for all AWS SDK calls
patch_all()

# Configure structured logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Environment configuration
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
MODEL_ID = os.environ.get("MODEL_ID", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
MAX_TOKENS = int(os.environ.get("MAX_TOKENS", "4096"))

# Multi-tenant configuration
TENANT_ID_HEADER = "x-tenant-id"


# =============================================================================
# State Definition
# =============================================================================

class AgentState(TypedDict):
    """State for the task-based agent.

    Attributes:
        task_input: The original task from the user
        tenant_id: Tenant identifier for multi-tenant isolation
        request_id: Unique request identifier for tracing
        steps: List of steps identified for the task
        current_step: Index of current step being executed
        intermediate_results: Results from each step
        final_result: The final output of the agent
        error: Error message if any step fails
        metadata: Additional metadata for logging/tracing
    """
    task_input: str
    tenant_id: str
    request_id: str
    steps: List[str]
    current_step: int
    intermediate_results: List[str]
    final_result: str
    error: Optional[str]
    metadata: dict


# =============================================================================
# Utility Functions
# =============================================================================

def extract_tenant_id(event: dict) -> str:
    """Extract tenant ID from API Gateway event.

    Checks authorizer context first, then falls back to headers.

    Args:
        event: API Gateway event

    Returns:
        Tenant ID string

    Raises:
        ValueError: If tenant_id is not found
    """
    # Try authorizer context first (from Cognito/custom authorizer)
    tenant_id = (
        event.get("requestContext", {})
        .get("authorizer", {})
        .get("claims", {})
        .get("custom:tenant_id")
    )

    # Fallback to custom authorizer context
    if not tenant_id:
        tenant_id = (
            event.get("requestContext", {})
            .get("authorizer", {})
            .get("tenant_id")
        )

    # Fallback to header
    if not tenant_id:
        headers = event.get("headers", {})
        tenant_id = headers.get(TENANT_ID_HEADER) or headers.get(TENANT_ID_HEADER.lower())

    if not tenant_id:
        raise ValueError("Missing tenant_id in request")

    return tenant_id


def log_with_context(level: str, message: str, tenant_id: str, request_id: str, **kwargs):
    """Log with tenant and request context for observability."""
    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "level": level,
        "message": message,
        "tenant_id": tenant_id,
        "request_id": request_id,
        **kwargs
    }
    if level == "ERROR":
        logger.error(json.dumps(log_entry))
    elif level == "WARNING":
        logger.warning(json.dumps(log_entry))
    else:
        logger.info(json.dumps(log_entry))


def create_bedrock_client(tenant_id: str) -> ChatBedrock:
    """Initialize Bedrock client with multi-tenant configuration.

    Args:
        tenant_id: Tenant identifier for request tagging

    Returns:
        Configured ChatBedrock instance
    """
    bedrock_client = boto3.client(
        "bedrock-runtime",
        region_name=AWS_REGION
    )

    return ChatBedrock(
        client=bedrock_client,
        model_id=MODEL_ID,
        model_kwargs={
            "max_tokens": MAX_TOKENS,
            "temperature": 0.7,
        },
        # Note: Add tenant tagging via request headers when supported
    )


# =============================================================================
# Agent Nodes
# =============================================================================

@xray_recorder.capture("analyze_task")
def analyze_task(state: AgentState) -> AgentState:
    """Analyze the task and break it into execution steps.

    This node uses the LLM to understand the task and create
    a plan of action.

    Args:
        state: Current agent state

    Returns:
        Updated state with steps populated
    """
    log_with_context(
        "INFO",
        "Analyzing task",
        state["tenant_id"],
        state["request_id"],
        task_length=len(state["task_input"])
    )

    try:
        llm = create_bedrock_client(state["tenant_id"])

        system_prompt = """You are a task analysis expert. Your job is to:
1. Understand the user's task
2. Break it down into 3-5 clear, actionable steps
3. Return ONLY the steps as a numbered list

Be specific and practical. Each step should be independently executable."""

        user_prompt = f"""Analyze this task and break it into execution steps:

Task: {state["task_input"]}

Provide 3-5 concrete steps to complete this task. Return only the numbered list."""

        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt)
        ])

        # Parse steps from response
        steps = []
        for line in response.content.strip().split("\n"):
            line = line.strip()
            if line and (line[0].isdigit() or line.startswith("-")):
                # Remove numbering/bullets
                step = line.lstrip("0123456789.-) ").strip()
                if step:
                    steps.append(step)

        if not steps:
            steps = ["Process the task as a single operation"]

        state["steps"] = steps
        state["current_step"] = 0

        log_with_context(
            "INFO",
            "Task analyzed",
            state["tenant_id"],
            state["request_id"],
            step_count=len(steps)
        )

    except Exception as e:
        state["error"] = f"Task analysis failed: {str(e)}"
        log_with_context(
            "ERROR",
            "Task analysis failed",
            state["tenant_id"],
            state["request_id"],
            error=str(e)
        )

    return state


@xray_recorder.capture("execute_step")
def execute_step(state: AgentState) -> AgentState:
    """Execute the current step in the task plan.

    Args:
        state: Current agent state

    Returns:
        Updated state with step result
    """
    if state.get("error"):
        return state

    current_idx = state["current_step"]
    if current_idx >= len(state["steps"]):
        return state

    current_step = state["steps"][current_idx]

    log_with_context(
        "INFO",
        f"Executing step {current_idx + 1}",
        state["tenant_id"],
        state["request_id"],
        step=current_step
    )

    try:
        llm = create_bedrock_client(state["tenant_id"])

        # Build context from previous steps
        context = ""
        if state["intermediate_results"]:
            context = "\n\nPrevious step results:\n"
            for i, result in enumerate(state["intermediate_results"]):
                context += f"Step {i + 1}: {result[:200]}...\n"

        prompt = f"""You are executing a step in a larger task.

Original Task: {state["task_input"]}

Current Step ({current_idx + 1}/{len(state["steps"])}): {current_step}
{context}

Execute this step and provide the result. Be concise but complete."""

        response = llm.invoke([HumanMessage(content=prompt)])

        state["intermediate_results"].append(response.content)
        state["current_step"] = current_idx + 1

        log_with_context(
            "INFO",
            f"Step {current_idx + 1} completed",
            state["tenant_id"],
            state["request_id"],
            result_length=len(response.content)
        )

    except Exception as e:
        state["error"] = f"Step {current_idx + 1} failed: {str(e)}"
        log_with_context(
            "ERROR",
            f"Step {current_idx + 1} failed",
            state["tenant_id"],
            state["request_id"],
            error=str(e)
        )

    return state


@xray_recorder.capture("synthesize_result")
def synthesize_result(state: AgentState) -> AgentState:
    """Synthesize final result from all step outputs.

    Args:
        state: Current agent state

    Returns:
        Updated state with final result
    """
    if state.get("error"):
        return state

    log_with_context(
        "INFO",
        "Synthesizing final result",
        state["tenant_id"],
        state["request_id"]
    )

    try:
        llm = create_bedrock_client(state["tenant_id"])

        # Compile all intermediate results
        results_summary = "\n\n".join([
            f"Step {i + 1} ({state['steps'][i]}):\n{result}"
            for i, result in enumerate(state["intermediate_results"])
        ])

        prompt = f"""You have completed a multi-step task. Now synthesize the final result.

Original Task: {state["task_input"]}

Step Results:
{results_summary}

Provide a clear, comprehensive final answer that addresses the original task.
Synthesize the step results into a coherent response."""

        response = llm.invoke([HumanMessage(content=prompt)])
        state["final_result"] = response.content

        log_with_context(
            "INFO",
            "Result synthesized",
            state["tenant_id"],
            state["request_id"],
            result_length=len(state["final_result"])
        )

    except Exception as e:
        state["error"] = f"Result synthesis failed: {str(e)}"
        # Fallback: concatenate intermediate results
        state["final_result"] = "\n\n".join(state["intermediate_results"])
        log_with_context(
            "WARNING",
            "Synthesis failed, using concatenated results",
            state["tenant_id"],
            state["request_id"],
            error=str(e)
        )

    return state


# =============================================================================
# Graph Construction
# =============================================================================

def should_continue_execution(state: AgentState) -> str:
    """Determine if we should continue executing steps or move to synthesis.

    Args:
        state: Current agent state

    Returns:
        Next node name: "execute_step", "synthesize", or "error"
    """
    if state.get("error"):
        return "end"

    if state["current_step"] < len(state["steps"]):
        return "execute_step"

    return "synthesize"


def create_agent_graph() -> StateGraph:
    """Create the LangGraph workflow for task execution.

    Returns:
        Compiled StateGraph
    """
    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("analyze", analyze_task)
    workflow.add_node("execute_step", execute_step)
    workflow.add_node("synthesize", synthesize_result)

    # Define edges
    workflow.set_entry_point("analyze")

    workflow.add_conditional_edges(
        "analyze",
        lambda s: "end" if s.get("error") else "execute_step",
        {
            "execute_step": "execute_step",
            "end": END
        }
    )

    workflow.add_conditional_edges(
        "execute_step",
        should_continue_execution,
        {
            "execute_step": "execute_step",
            "synthesize": "synthesize",
            "end": END
        }
    )

    workflow.add_edge("synthesize", END)

    return workflow.compile()


# =============================================================================
# Lambda Handler
# =============================================================================

# Initialize agent graph at module load (warm start optimization)
agent_graph = create_agent_graph()


def lambda_handler(event: dict, context) -> dict:
    """AWS Lambda handler for the task-based agent.

    Expected request body:
    {
        "task": "The task to complete"
    }

    Args:
        event: API Gateway event
        context: Lambda context

    Returns:
        API Gateway response with result or error
    """
    request_id = context.aws_request_id if context else "local-" + datetime.utcnow().isoformat()

    try:
        # Extract tenant ID
        tenant_id = extract_tenant_id(event)

        log_with_context(
            "INFO",
            "Request received",
            tenant_id,
            request_id,
            path=event.get("path"),
            method=event.get("httpMethod")
        )

        # Parse request body
        body = json.loads(event.get("body", "{}"))
        task_input = body.get("task")

        if not task_input:
            return {
                "statusCode": 400,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({
                    "error": "Missing 'task' in request body",
                    "request_id": request_id
                })
            }

        # Initialize state
        initial_state: AgentState = {
            "task_input": task_input,
            "tenant_id": tenant_id,
            "request_id": request_id,
            "steps": [],
            "current_step": 0,
            "intermediate_results": [],
            "final_result": "",
            "error": None,
            "metadata": {
                "start_time": datetime.utcnow().isoformat(),
                "model_id": MODEL_ID
            }
        }

        # Execute agent graph
        final_state = agent_graph.invoke(initial_state)

        # Check for errors
        if final_state.get("error"):
            log_with_context(
                "ERROR",
                "Agent execution failed",
                tenant_id,
                request_id,
                error=final_state["error"]
            )
            return {
                "statusCode": 500,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({
                    "error": final_state["error"],
                    "request_id": request_id
                })
            }

        # Success response
        log_with_context(
            "INFO",
            "Request completed successfully",
            tenant_id,
            request_id,
            steps_executed=len(final_state["steps"])
        )

        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "result": final_state["final_result"],
                "steps_executed": final_state["steps"],
                "request_id": request_id
            })
        }

    except ValueError as e:
        # Tenant ID missing or invalid
        return {
            "statusCode": 403,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": str(e),
                "request_id": request_id
            })
        }

    except json.JSONDecodeError:
        return {
            "statusCode": 400,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": "Invalid JSON in request body",
                "request_id": request_id
            })
        }

    except Exception as e:
        logger.exception("Unexpected error")
        return {
            "statusCode": 500,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({
                "error": "Internal server error",
                "request_id": request_id
            })
        }


# =============================================================================
# Local Testing
# =============================================================================

if __name__ == "__main__":
    # Test event
    test_event = {
        "requestContext": {
            "authorizer": {
                "tenant_id": "test-tenant-123"
            }
        },
        "headers": {},
        "body": json.dumps({
            "task": "{{USE_CASE}}"
        })
    }

    # Mock context
    class MockContext:
        aws_request_id = "local-test-123"

    result = lambda_handler(test_event, MockContext())
    print(json.dumps(json.loads(result["body"]), indent=2))
